pipeline:

  deploy_to_notprod:
    image: quay.io/ukhomeofficedigital/kd
    environment:
      - KUBE_NAMESPACE=dq-apps-notprod
      - INSECURE_SKIP_TLS_VERIFY=true
      - URL=analysis.staging.notprod.dq.homeoffice.gov.uk
    commands:
      - export KUBE_TOKEN=$$NOTPROD_KUBE_TOKEN
      - export KUBE_SERVER=$$NOTPROD_KUBE_SERVER
      - kd -f network-policy.yaml -f service.yaml -f ingress.yaml -f deployment.yaml
    secrets:
      - NOTPROD_KUBE_TOKEN
      - NOTPROD_KUBE_SERVER
    when:
      event: push
      branch: master

  # deploy_to_prod:
  #   image: quay.io/ukhomeofficedigital/kd
  #   environment:
  #     - KUBE_NAMESPACE=dq-apps
  #     - INSECURE_SKIP_TLS_VERIFY=true
  #     - URL=analysis.staging.dq.homeoffice.gov.uk
  #   commands:
  #     - export KUBE_TOKEN=$$PROD_KUBE_TOKEN
  #     - export KUBE_SERVER=$$PROD_KUBE_SERVER
  #     - kd -f network-policy.yaml -f service.yaml -f ingress.yaml -f deployment.yaml
  #   secrets:
  #     - PROD_KUBE_TOKEN
  #     - PROD_KUBE_SERVER
  #
  #   when:
  #     environment: production
  #     event: deployment
